### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by pemarko** [BrainicHQ/tado-assistant#9]
Hi there,

First, thanks for putting this together. I'm trying to setup this on my rpi-zerow, but I immediatelly hit login error:
{"error":"invalid_grant","error_description":"Bad credentials"}

Is this still working for you? curl command for fetching token contains client_id and client_secret which seem to changed. Any idea how to get this working again?

Thx

**Comment by s1lviu** [comment]
Hi, it was just a redundant call which I fixed here https://github.com/BrainicHQ/tado-assistant/commit/459859a393dc581cb6e4d30473496b290d34beb6 and shouldn't impact the functionality in any way. 
Waiting for your confirmation.
Thanks!

**Comment by pemarko** [comment]
Hi s1lviu,

actually I was getting this even in service script not only during install.sh. 
I've tried curl command to fetch token manually and it was failing too. So after numerous attempts I've decided to change password which contained '$' character. I though that --data-urlencode should take care of it, but it didn't. Seems to be an issue how server parses password string. 
After changing password to aplha-num only, login is working in both manual and inside script mode.

**Comment by s1lviu** [comment]
That's right. I managed to provide a fix. Can you try again, please, with the password that contained special chars like '$'? Thanks!

**Comment by pemarko** [comment]
Btw, what's the procedure/config-options to disable geofencing to force my home status to Away? I want to disable geofencing permanently, but script decides that when no-devices are home and status is home then it sets it away. 
Going to try fix.

**Comment by pemarko** [comment]
I've done:
git pull (btw install --update runs under root and changes permission in .git)
install.sh --update

but login still fails for password containing $ character. It's probably issue on tado server side.

**Comment by pemarko** [comment]
Got three solutions that work for password with $:
1. manually escape $ e.g.:   --data-urlencode "password=mypasswith\\$sign"

2. putting cleatext password into single quotes:  --data-urlencode 'password=mypasswith$sign'

3. Version with variable:
MYPASS='mypasswith$sign'
--data-urlencode "password=$MYP"

**Comment by s1lviu** [comment]
> Btw, what's the procedure/config-options to disable geofencing to force my home status to Away? I want to disable geofencing permanently, but script decides that when no-devices are home and status is home then it sets it away. Going to try fix.

You can try to disable the geofencing for that devices from the tado mobile app, Geofencing section, or modify the script to eliminate the calls that are updating the home status.



> I've done: git pull (btw install --update runs under root and changes permission in .git) install.sh --update
> 
> but login still fails for password containing $ character. It's probably issue on tado server side.

Strange. I just tested with my account with a '$' in the password and it worked.

**Comment by pemarko** [comment]
so probably a shell issue. I'm on raspberryos 32-bit latest version, using bash  5.2.15(1)-release (arm-unknown-linux-gnueabihf)

**Comment by s1lviu** [comment]
> so probably a shell issue. I'm on raspberryos 32-bit latest version, using bash 5.2.15(1)-release (arm-unknown-linux-gnueabihf)

I pushed my last fix idea. Otherwise, I'll let your issue open, maybe someone will want to contribute to a more comprehensive fix.

**Comment by pemarko** [comment]
with your latest changes, it still fails, but when adding single quotes into .env file then it works:

export TADO_PASSWORD_1='mypasswith$sign'

So I'm pretty happy with this.

**Comment by s1lviu** [comment]
> with your latest changes, it still fails, but when adding single quotes into .env file then it works:
> 
> export TADO_PASSWORD_1='mypasswith$sign'
> 
> So I'm pretty happy with this.

Oh, ok. Can you update and give a superfinal try?

**Comment by pemarko** [comment]
Perfect!

I've run uninstall steps, install from scratch and it's working!

**Comment by s1lviu** [comment]
Great! Enjoy!
